workspace 'NewsAPIKit.xcworkspace'

platform :ios, '10.0'
use_frameworks!

def newsAPIKit_pods
  pod 'Moya', "~>14.0.0"
end

target 'NewsAPIKit' do
  newsAPIKit_pods
end

target 'NewsAPIKitTests' do
  newsAPIKit_pods
end
