workspace 'NewsAPIKit.xcworkspace'

platform :ios, '8.0'
use_frameworks!

def newsAPIKit_pods
  pod 'Moya'
end

target 'NewsAPIKit' do
  newsAPIKit_pods
end

target 'NewsAPIKitTests' do
  newsAPIKit_pods
end
